title: Willson's Blog
email: willsoncen@example.com
description: >- 
  个人技术博客 - 分享编程经验、学习心得和技术见解
baseurl: ""
url: ""
github_username: willsoncen

# 添加个人信息
author:
  name: Willson Cen
  bio: Full Stack Developer | Open Source Enthusiast
  location: China
  avatar: /assets/images/avatar.jpg
  social:
    github: willsoncen
    twitter: willsoncen
    linkedin: willsoncen

# 显示设置
show_excerpts: true
show_author: true
header_pages:
  - about.md
  - projects.md
  - categories.md

theme: minima
plugins:
  - jekyll-feed
